INFO     root:HmsManager.py:28 2023-01-20 16:48:03: login HMS, ip: 172.16.2.220,username: root
INFO     root:HmsManager.py:30 2023-01-20 16:48:03: login HMS success!
INFO     root:HmsManager.py:46 2023-01-20 16:48:03: query gnb info
INFO     root:HmsManager.py:48 2023-01-20 16:48:03: enbId/enbName:4/Automatic-18
INFO     root:CpeManager.py:28 2023-01-20 16:48:03: login cpe command model
INFO     paramiko.transport:transport.py:1874 Connected (version 2.0, client dropbear)
INFO     paramiko.transport:transport.py:1874 Authentication (password) successful!
INFO     root:cpeModel.py:35 login cpe success!
WARNING  root:test_phy.py:251 2023-01-20 16:48:03: confirm if support PRACH format, index value:147
INFO     root:PdcchManager.py:120 2023-01-20 16:48:03: modify PRACH configuration index, index value:147
INFO     root:PdcchManager.py:126 2023-01-20 16:48:08: PRACH configuration index modify success!
INFO     root:CellManager.py:58 2023-01-20 16:48:08: confirm if cell status is same as expect status,expect status:available
INFO     root:CellManager.py:26 2023-01-20 16:48:08: query cell status
INFO     root:CellManager.py:36 2023-01-20 16:48:09: cell status:available
INFO     root:CellManager.py:65 2023-01-20 16:48:09: cell status:available, expect status:available
INFO     root:CpeManager.py:429 2023-01-20 16:48:09: start ue log trace
INFO     root:qutsModel.py:88 printing the chip name of the first device with DIAG_PROT:
INFO     root:qutsModel.py:92 SDX55
INFO     root:qutsModel.py:110 QXDM automation interface successfully launched
INFO     root:qutsModel.py:114 connecting to device with devicehandle=1970324836974592, len=16; protoHandle=1970329131941888, len=16
INFO     root:qutsModel.py:120 QXDM successfully connects to device with deviceHandle=1970324836974592, protHandle=1970329131941888
INFO     root:CpeManager.py:46 2023-01-20 16:48:19: exec attach command
INFO     root:cpeModel.py:58 AT Command is:at+cfun=1
INFO     root:cpeModel.py:82 mattch result is:['root@OpenWrt:~# at_cmd_task', 'OK']
INFO     root:CpeManager.py:120 2023-01-20 16:48:23: confirm if pdu setup success
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:126 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-01-20 16:48:29: wait for 5s......
INFO     root:qutsModel.py:38 Message Received Invalid HDLC Frame Bad CRC check for HDLC frame found from Diag protocol: 2500->::ffff:192.168.1.1
INFO     root:cpeModel.py:129 ip info mattch result is['190.1.2.163', '190.3.2.140']
INFO     root:basic.py:30 2023-01-20 16:48:39: wait for 10s......
INFO     root:qutsModel.py:38 Message Received Error no response:  Device did not respond to Diag request Error no response: Diag protocol failed to respond to Diag request: 2500->::ffff:192.168.1.1 - Command code: 123
INFO     root:CpeManager.py:439 2023-01-20 16:48:49: stop ue log trace
INFO     root:qutsModel.py:136 hdf is saved to ['D:\\autotestPro\\AutoTestMain\\qxdmLog\\71bb7cf1-3ece-4375-9d92-44f77062d7e3_50491_Diag_2500-ffff192_168_1_1_0.hdf']
INFO     root:CpeManager.py:562 2023-01-20 16:48:49: PRACH config index params analyze, index:147
INFO     root:qCatModel.py:46 Open Ue Log Success
INFO     root:CpeManager.py:572 2023-01-20 16:48:51: check result is:{'prachConfig': True, 'preambleFormat': True}
INFO     root:CpeManager.py:62 2023-01-20 16:48:51: exec detach command
INFO     root:cpeModel.py:58 AT Command is:at+cfun=0
INFO     root:cpeModel.py:82 mattch result is:['', 'OK']
INFO     root:test_phy.py:270 2023-01-20 16:48:55: move the log file to backup folder